//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int Id { get; set; }
        public int IdTipoCombustivel { get; set; }
        public int IdCilindradas { get; set; }
        public int QuantidadePortas { get; set; }
        public int QuantidadeValvulas { get; set; }
    
        public virtual Cilindradas Cilindradas { get; set; }
        public virtual TipoCombustivel TipoCombustivel { get; set; }
    }
}
